feat: update matplotlib to 3.6.3

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -9,6 +9,34 @@ version: 2.1
 #
 
 commands:
+  check-skip:
+    steps:
+      - run:
+          name: Check-skip
+          command: |
+            export git_log=$(git log --max-count=1 --pretty=format:"%B" | tr "\n" " ")
+            echo "Got commit message:"
+            echo "${git_log}"
+            if [[ -v CIRCLE_PULL_REQUEST ]] && ([[ "$git_log" == *"[skip circle]"* ]] || [[ "$git_log" == *"[circle skip]"* ]]); then
+              echo "Skip detected, exiting job ${CIRCLE_JOB} for PR ${CIRCLE_PULL_REQUEST}."
+              circleci-agent step halt;
+            fi
+
+  merge:
+    steps:
+      - run:
+          name: Merge with upstream
+          command: |
+            if ! git remote -v | grep upstream; then
+              git remote add upstream https://github.com/matplotlib/matplotlib.git
+            fi
+            git fetch upstream
+            if [[ "$CIRCLE_BRANCH" != "main" ]] && \
+               [[ "$CIRCLE_PR_NUMBER" != "" ]]; then
+              echo "Merging ${CIRCLE_PR_NUMBER}"
+              git pull --ff-only upstream "refs/pull/${CIRCLE_PR_NUMBER}/merge"
+            fi
+
   apt-install:
     steps:
       - run:
@@ -27,10 +55,12 @@ commands:
               texlive-latex-recommended \
               texlive-pictures \
               texlive-xetex \
+              ttf-wqy-zenhei \
               graphviz \
               fonts-crosextra-carlito \
               fonts-freefont-otf \
               fonts-humor-sans \
+              fonts-noto-cjk \
               optipng
 
   fonts-install:
@@ -54,11 +84,11 @@ commands:
       - run:
           name: Upgrade pip, setuptools, wheel
           command: |
-            python -mpip install --upgrade --user pip
-            python -mpip install --upgrade --user wheel
-            python -mpip install --upgrade --user setuptools
+            python -m pip install --upgrade --user pip
+            python -m pip install --upgrade --user wheel
+            python -m pip install --upgrade --user 'setuptools!=60.6.0'
 
-  deps-install:
+  doc-deps-install:
     parameters:
       numpy_version:
         type: string
@@ -67,14 +97,32 @@ commands:
       - run:
           name: Install Python dependencies
           command: |
-            python -mpip install --user numpy<< parameters.numpy_version >> codecov coverage
-            python -mpip install --user -r requirements/doc/doc-requirements.txt
+            python -m pip install --no-deps --user \
+                git+https://github.com/matplotlib/mpl-sphinx-theme.git
+            python -m pip install --user \
+                numpy<< parameters.numpy_version >> codecov coverage \
+                -r requirements/doc/doc-requirements.txt
 
   mpl-install:
     steps:
       - run:
           name: Install Matplotlib
-          command: python -mpip install --user -ve .
+          command: |
+            if [[ "$CIRCLE_BRANCH" == v*-doc ]]; then
+              # The v*-doc branches must build against the specified release.
+              version=${CIRCLE_BRANCH%-doc}
+              version=${version#v}
+              python -m pip install matplotlib==${version}
+            else
+              python -m pip install --user -ve .
+            fi
+      - save_cache:
+          key: build-deps-1
+          paths:
+            # FreeType 2.6.1 tarball.
+            - ~/.cache/matplotlib/0a3c7dfbda6da1e8fce29232e8e96d987ababbbf71ebc8c75659e4132c367014
+            # Qhull 2020.2 tarball.
+            - ~/.cache/matplotlib/b5c2d7eb833278881b952c8a52d20179eab87766b00b865000469a45c1838b7e
 
   doc-build:
     steps:
@@ -87,7 +135,13 @@ commands:
           command: |
             # Set epoch to date of latest tag.
             export SOURCE_DATE_EPOCH="$(git log -1 --format=%at $(git describe --abbrev=0))"
-            make html O=-T
+            # Set release mode only when deploying to devdocs.
+            if [ "$CIRCLE_PROJECT_USERNAME" = "matplotlib" ] && \
+               [ "$CIRCLE_BRANCH" = "main" ] && \
+               [ "$CIRCLE_PR_NUMBER" = "" ]; then
+              export RELEASE_TAG='-t release'
+            fi
+            make html O="-T $RELEASE_TAG -j4 -w /tmp/sphinxerrorswarnings.log"
             rm -r build/html/_sources
           working_directory: doc
       - save_cache:
@@ -95,11 +149,36 @@ commands:
           paths:
             - doc/build/doctrees
 
+  doc-show-errors-warnings:
+    steps:
+      - run:
+          name: Extract possible build errors and warnings
+          command: |
+           (grep "WARNING\|ERROR" /tmp/sphinxerrorswarnings.log ||
+            echo "No errors or warnings")
+          when: always
+
+  doc-show-deprecations:
+    steps:
+      - run:
+          name: Extract possible deprecation warnings in examples and tutorials
+          command: |
+           (grep DeprecationWarning -r -l doc/build/html/gallery ||
+            echo "No deprecation warnings in gallery")
+           (grep DeprecationWarning -r -l doc/build/html/tutorials ||
+            echo "No deprecation warnings in tutorials")
+          when: always
+
   doc-bundle:
     steps:
       - run:
           name: Bundle sphinx-gallery documentation artifacts
-          command: tar cf doc/build/sphinx-gallery-files.tar.gz doc/api/_as_gen doc/gallery doc/tutorials
+          command: >
+            tar cf doc/build/sphinx-gallery-files.tar.gz
+            doc/api/_as_gen
+            doc/gallery
+            doc/plot_types
+            doc/tutorials
           when: always
       - store_artifacts:
           path: doc/build/sphinx-gallery-files.tar.gz
@@ -110,69 +189,36 @@ commands:
 #
 
 jobs:
-  docs-python36:
-    docker:
-      - image: circleci/python:3.6
-    steps:
-      - checkout
-
-      - apt-install
-      - fonts-install
-      - pip-install
-      - deps-install:
-          numpy_version: "==1.13.0"
-      - mpl-install
-
-      - doc-build
-
-      - doc-bundle
-
-      - store_artifacts:
-          path: doc/build/html
-
-  docs-python37:
-    docker:
-      - image: circleci/python:3.7
-    steps:
-      - checkout
-
-      - apt-install
-      - fonts-install
-      - pip-install
-
-      - deps-install
-      - mpl-install
-
-      - doc-build
-
-      - doc-bundle
-
-      - store_artifacts:
-          path: doc/build/html
-
   docs-python38:
     docker:
-      - image: circleci/python:3.8
+      - image: cimg/python:3.8
+    resource_class: large
     steps:
       - checkout
+      - check-skip
+      - merge
 
       - apt-install
       - fonts-install
       - pip-install
 
-      - deps-install
       - mpl-install
+      - doc-deps-install
 
       - doc-build
+      - doc-show-errors-warnings
+      - doc-show-deprecations
 
       - doc-bundle
 
       - store_artifacts:
           path: doc/build/html
+      - store_test_results:
+          path: doc/build/test-results
 
       - add_ssh_keys:
           fingerprints:
-            - "78:13:59:08:61:a9:e5:09:af:df:3a:d8:89:c2:84:c0"
+            - "6b:83:76:a5:7d:bd:ce:19:a4:e3:81:e0:80:16:a4:fe"
       - deploy:
           name: "Deploy new docs"
           command: ./.circleci/deploy-docs.sh
@@ -185,6 +231,6 @@ workflows:
   version: 2
   build:
     jobs:
-      - docs-python36
-      - docs-python37
+      # NOTE: If you rename this job, then you must update the `if` condition
+      # and `circleci-jobs` option in `.github/workflows/circleci.yml`.
       - docs-python38
